server.port=8080
devshield.analyzer.url=http://localhost:8001/analyze
spring.jackson.serialization.indent-output=false
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=500MB
